[workspace]
members = [
    "core",
    "gamerplex-math",
    "ecs",
    "renderer",
    "gamerplex-physics",
    "audio",
    "input",
    "resources",
    "scripting",
    "debug",
    "examples",
]

resolver = "2"